import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Button } from "@/components/ui/button";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 text-gray-900`}
      >
        {/* Header */}
        <header className="flex justify-between items-center p-4 border-b bg-white shadow-md">
          <h1 className="text-xl font-bold">My App</h1>
          <Button variant="outline">Sign In</Button>
        </header>

        {/* Main Content */}
        <main className="flex-grow">{children}</main>

        {/* Footer */}
        <footer className="p-4 text-center border-t bg-gray-100">
          &copy; {new Date().getFullYear()} My App. All rights reserved.
        </footer>
      </body>
    </html>
  );
}
